### ISSUE TITLE
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option

### ISSUE THREAD

**Issue by st-clair-clarke** [pleerock/event-dispatch#1]
Hi,
I keep getting similar errors

I have es6-shim installed and I am able to access Map, Set etc.
The the 'experimentalDecorators' option is also set in typscript.json.

I have the following class

## EventSubscriber

```typescript
import {EventSubscriber, On} from "event-dispatch";
import {Language} from './language.model'

@EventSubscriber()
export class LanguageEventSubscriber {
	@On('onSubmitValidLanguage')
    onSubmitValidLanguage(language: Language) {
        console.log("User " + language + " created!");
    }

    @On('onSubmitInvalidLanguage')
    onSubmitInvalidLanguage(status: string) {
        console.log("New status: " + status);
    }
}
```

## Language

```typescript
import {autoserialize} from 'cerialize'
import {sanitize, Trim, Rtrim, Blacklist} from "class-sanitizer";
import {IsLength, MinLength, MaxLength} from "class-validator";

const msg: string = "Minimum characters ➔ 2"

export class Language {
	@autoserialize
	@MinLength(10, { message: msg })
	@MaxLength(50, { message: "Title is too long" })
	@IsLength(10, 20, {message: 'Wrong lenght'})
	@Trim()
	first: string = ''
	@autoserialize second: string = ''

	isValid: boolean = false
}
```

Observe the errors in the graphic below

![lang-event](https://cloud.githubusercontent.com/assets/3227590/16288680/8e4c58b8-38bc-11e6-8e49-9aeec7cc8ef2.jpg)

The error generated in Sublime Text 3 is shown below

J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts [2 errors]
    (24, 15) Cannot find name 'Map'.
    (26, 16) Cannot find name 'Map'.
J:/workspace/angular2/ts/epimss/node_modules/class-validator/Validator.d.ts [1 errors]
    (20, 71) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/reflection/reflector.d.ts [5 errors]
    (28, 22) Cannot find name 'Map'.
    (30, 15) Cannot find name 'Map'.
    (32, 15) Cannot find name 'Map'.
    (34, 15) Cannot find name 'Map'.
    (36, 16) Cannot find name 'Set'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/facade/lang.d.ts [3 errors]
    (4, 17) Cannot find name 'Map'.
    (5, 17) Cannot find name 'Set'.
    (70, 59) Cannot find name 'Map'.
J:/workspace/angular2/ts/epimss/src/app/registration/language/language-event-subscriber.ts [5 errors]
    (11, 2) Expression expected.
    (16, 14) Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
    (18, 5) Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
    (19, 31) Cannot find name 'user'.
    (23, 5) Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
J:/workspace/angular2/ts/epimss/src/app/registration/language/language.model.ts [2 errors]
    (18, 2) Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
    (24, 2) Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/application_ref.d.ts [3 errors]
    (39, 88) Cannot find name 'Promise'.
    (99, 42) Cannot find name 'Promise'.
    (174, 33) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/testing/mock_application_ref.d.ts [1 errors]
    (12, 33) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts [4 errors]
    (62, 148) Cannot find name 'Promise'.
    (103, 144) Cannot find name 'Promise'.
    (108, 139) Cannot find name 'Promise'.
    (109, 135) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/class-sanitizer/index.d.ts [1 errors]
    (8, 54) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/facade/async.d.ts [2 errors]
    (27, 33) Cannot find name 'Promise'.
    (28, 45) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/facade/promise.d.ts [10 errors]
    (2, 14) Cannot find name 'Promise'.
    (8, 32) Cannot find name 'Promise'.
    (9, 38) Cannot find name 'Promise'.
    (10, 35) Cannot find name 'Promise'.
    (10, 93) Cannot find name 'Promise'.
    (11, 34) Cannot find name 'Promise'.
    (11, 50) Cannot find name 'Promise'.
    (12, 32) Cannot find name 'Promise'.
    (12, 149) Cannot find name 'Promise'.
    (13, 43) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/linker/component_resolver.d.ts [2 errors]
    (8, 53) Cannot find name 'Promise'.
    (12, 44) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/rxjs/Observable.d.ts [3 errors]
    (10, 66) Cannot find name 'Promise'.
    (66, 60) Cannot find name 'Promise'.
    (66, 70) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/testability/testability.d.ts [1 errors]
    (40, 20) Cannot find name 'Map'.
J:/workspace/angular2/ts/epimss/node_modules/class-sanitizer/Sanitizer.d.ts [1 errors]
    (18, 34) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/class-validator/index.d.ts [1 errors]
    (11, 91) Cannot find name 'Promise'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/facade/collection.d.ts [13 errors]
    (1, 25) Cannot find name 'MapConstructor'.
    (2, 25) Cannot find name 'SetConstructor'.
    (4, 27) Cannot find name 'Map'.
    (4, 39) Cannot find name 'Map'.
    (7, 9) Cannot find name 'Map'.
    (8, 30) Cannot find name 'Map'.
    (11, 43) Cannot find name 'Map'.
    (12, 27) Cannot find name 'Map'.
    (14, 23) Cannot find name 'Map'.
    (15, 25) Cannot find name 'Map'.
    (100, 41) Cannot find name 'Set'.
    (101, 22) Cannot find name 'Set'.
    (102, 25) Cannot find name 'Set'.
J:/workspace/angular2/ts/epimss/node_modules/@angular/core/src/di/reflective_provider.d.ts [2 errors]
    (105, 123) Cannot find name 'Map'.
    (105, 165) Cannot find name 'Map'.

The problem seems that the installed es6-shim is not recognised. Yet in the Language class, there is no such issues.

Thanks

**Comment by pleerock** [comment]
have you installed es6-shim typings?

**Comment by st-clair-clarke** [comment]
Yes. And I was able to use Map from the package.

**Comment by pleerock** [comment]
this error doesnt seem to be related to event-dispatch. If you remove event-dispatch will your project compile without errors? try it, because I doubt that its because of this library, because you have errors in other parts too

**Comment by st-clair-clarke** [comment]
The application does run even with the errors.

**Comment by pleerock** [comment]
again, if you remove  event-dispatch will it give errors or not?

**Comment by soromamadou** [comment]
if you are using visual code:
1- Add new folder ".vscode"  at the root of your projet. If the root of your projet is not your angular or react folder, then add in the first directory in your visual code project
2- add new file settings.json in this '.vscode' folder
3- write into settings.json following
 : 
{
    "typescript.tsdk": "node_modules/typescript/lib/"
}
