### ISSUE TITLE
Registering an EventSubscriber

### ISSUE THREAD

**Issue by st-clair-clarke** [pleerock/event-dispatch#2]
I have the following src

## language.model.ts

```typescript
export class Language {
	first: string = ''
       second: string = ''
	isValid: boolean = false
}
```

### language-event-subscriber

```typescript
import {EventSubscriber, On} from "event-dispatch";

import {Language} from './language.model'

@EventSubscriber()
export class LanguageEventSubscriber {
	@On('onValidLanguage')
    onValidLanguage(language: Language) {
        console.log("Valid language!");
    }

    @On('onInvalidLanguage')
    onInvalidLanguage(status: string) {
        console.log("New status: ");
    }
}
```

## language.component.ts
import {LanguageEventSubscriber} from './language-event-subscriber'

```typescript

....

ngOnInit
this.submitBtnClick$
      .subscribe((event) => {
                this.eventDispatcher.dispatch('onValidLanguage', this.language)
      })
  }
```

The above does NOT print anything to the console.

In dispatch-event docs you said that 
### // note that all your subscribers must be imported somewhere in the app, so they are getting registered

But even though I imported the EventLanguageSubscriber in the language.component.ts, nothing is printed.  I am afraid I am doing something wrong.

Hope you can help.

Thanks

**Comment by pleerock** [comment]
most probably you are doing something wrong. put console.log in `language-event-subscriber` and make sure its being loaded

**Comment by st-clair-clarke** [comment]
The language-event-subscriber is NOT being called. log statements before and after `this.eventDispatcher.dispatch('onValidLanguage', this.language) `
are called, but NOT the language-event-subscriber.

**Comment by pleerock** [comment]
can you show how do you initialize it?

**Comment by pleerock** [comment]
`console.log` in language-event-subscriber is not being called, right?

**Comment by st-clair-clarke** [comment]
console.log in language-event-subscriber is NOT being called. Hence I was asking how do you initialize the  LanguageEventSubscriber class. It is imported, but now where in your docs I see where are how to initialize it. There is only a statement bout importing it.

**Comment by pleerock** [comment]
yeah it should be enought. Can you show how are you importing it? just copy/paste that line

**Comment by st-clair-clarke** [comment]
```typescript
import {LanguageEventSubscriber} from './language-event-subscriber'
```

where

##language-event-subscriber
contains

```typescript
import {EventSubscriber, On} from "event-dispatch";

import {Language} from './language.model'

@EventSubscriber()
export class LanguageEventSubscriber {
  constructor()
  {
    console.log("LanguageEventSubscriber constructed");
  }

	@On('onValidLanguage')
    onValidLanguage(language: Language) {
        console.log("Valid language!");
    }

    @On('onInvalidLanguage')
    onInvalidLanguage(status: string) {
        console.log("New status: ");
    }
}

```

**Comment by pleerock** [comment]
its not right importing. Where do you import it? You should import it in a global place like `app.ts`, and import should be like this: `import  './language-event-subscriber'`

**Comment by st-clair-clarke** [comment]
I am using angular2 with typescript 1.8. All my imports are done similarly without any errors and are found at runtime. I admit that the import is NOT done in app.ts, I will import it in app.ts and see

**Comment by pleerock** [comment]
yeah try it, and import only this way: `import './language-event-subscriber'`

**Comment by st-clair-clarke** [comment]
You are CORRECT. I imported it as you suggested and it worked. My original import does not work. Is this method of import new. I have not seen it in any docs. I wonder if this might be causing problems at other places in my code. Can you send me a link of where you found that method of importing?

When I use the method of import you suggested, I don't have to put the event class in app.ts, it worked in its original position in the language folder.

Thanks a million for being patient and so helpful.

**Comment by pleerock** [comment]
its standard way of importing, try to find it in typescript docs
