### ISSUE TITLE
Failed resolution of imports EventsHandler and EventSubscriberInterface

### ISSUE THREAD

**Issue by st-clair-clarke** [pleerock/event-dispatch#3]
Hi,
The following imports are not resolving in my application:

```typescript
import {EventSubscriberInterface} from 'event-dispatch'
import {EventsHandler}  from 'event-dispatch'
```
Note the other imports are resolved as shown in the graphic below which also shows the reason for the failure.

![event-dispatch1](https://cloud.githubusercontent.com/assets/3227590/16363669/e8e77d4e-3b9f-11e6-8934-60f187564e95.jpg)

The following graphic shows that the classes are available, but are not a part of the index.js that seems to be parsed

![event-dispatch2](https://cloud.githubusercontent.com/assets/3227590/16363673/f2d40b92-3b9f-11e6-8101-ed96d6f61c91.jpg)

Thanks for your help.

**Comment by pleerock** [comment]
maybe its not exported in index.ts... Try to import directly:
```import {EventSubscriberInterface} from 'event-dispatch/EventSubscriberInterface'```

**Comment by st-clair-clarke** [comment]
Worked and thanks.
